import chickenSalad from "../assets/images/products/som_tam_papaya_salad.png";
import tomYam from "../assets/images/products/tom_yam.png";
import tomKha from "../assets/images/products/tom_kha.png";
import sweetNsourChicken from "../assets/images/products/sweet_n_sour.png";
import chickenCashew from "../assets/images/products/sweet_n_sour.png";
import kaiSeeEw from "../assets/images/products/kai_see_ew.png";
import beefMassaman from "../assets/images/products/beef_massaman.png";
import chuChee from "../assets/images/products/chu_chee.png";
import redCurry from "../assets/images/products/red_curry.png";
import greenCurry from "../assets/images/products/green_curry.png";
import tofuCashew from "../assets/images/products/tofu_cashew.png";
import krapauVega from "../assets/images/products/krapau_vega.png";
import kroepoek from "../assets/images/products/kroepoek.png";
import fishCakes from "../assets/images/products/fish_cakes.png";
import sate from "../assets/images/products/sate.png";
import satesaus from "../assets/images/products/satesaus.png";
import koongHomPha from "../assets/images/products/koong_hom_pha.png";
import springRolls from "../assets/images/products/mini_vega_springrolls.png";
import friedRice from "../assets/images/products/fried_rice.png";
import prikNamPla from "../assets/images/products/prik_nam_pla.png";
import stirFriedVegetables from "../assets/images/products/stir_fried_vegetables.png";
import witteRijst from "../assets/images/products/witte_rijst.png";
import friedNoodles from "../assets/images/products/fried_noodles.png";
import kingSalad from "../assets/images/products/king_salad.png";

const products = [
  {
    name: "Laab kai chicken salad",
    price: 10,
    category: "salads",
    image: chickenSalad,
    id: "laab-kai-chicken-salad",
    nuts: true,
    vegeterian: false,
    spiciness: 2,
  },
  {
    name: "Som tam papaya salad",
    price: 9.5,
    category: "salads",
    image: chickenSalad,
    id: "som-tam-papaya-salad",
    nuts: false,
    vegeterian: true,
    spiciness: 0,
  },
  {
    name: "Tom yam kai",
    price: 7,
    category: "soups",
    image: tomYam,
    id: "tom-yam-kai",
    nuts: false,
    vegeterian: false,
    spiciness: 3,
  },
  {
    name: "Tom kha kai",
    price: 7,
    category: "soups",
    image: tomKha,
    id: "tom-kha-kai",
    nuts: false,
    vegeterian: false,
    spiciness: 3,
  },
  {
    name: "Tom kha koong",
    price: 8,
    category: "soups",
    image: tomKha,
    id: "tom-kha-koong",
    nuts: false,
    vegeterian: false,
    spiciness: 2,
  },
  {
    name: "Tom yam koong",
    price: 8,
    category: "soups",
    image: tomYam,
    id: "tom-yam-koong",
    nuts: false,
    vegeterian: false,
    spiciness: 4,
  },
  {
    name: "Tom yam vegetarian",
    price: 7,
    category: "soups",
    image: tomYam,
    id: "tom-yam-vegetarian",
    nuts: false,
    vegeterian: true,
    spiciness: 1,
  },
  {
    name: "Tom kha vegetarian",
    price: 7,
    category: "soups",
    image: tomKha,
    id: "tom-kha-vegetarian",
    nuts: false,
    vegeterian: true,
    spiciness: 1,
  },
  {
    name: "Sweet 'n sour chicken",
    price: 14,
    category: "chicken-dishes",
    image: sweetNsourChicken,
    id: "sweet-n-sour-chicken",
    nuts: true,
    vegeterian: false,
    spiciness: 2,
  },
  {
    name: "Chicken cashew",
    price: 14,
    category: "chicken-dishes",
    image: chickenCashew,
    id: "chicken-cashew",
    nuts: true,
    vegeterian: false,
    spiciness: 1,
  },
  {
    name: "Kai see ew",
    price: 14,
    category: "chicken-dishes",
    image: kaiSeeEw,
    id: "kai-see-ew",
    nuts: false,
    vegeterian: false,
    spiciness: 4,
  },
  {
    name: "Beef massaman",
    price: 14.5,
    category: "beef-dishes",
    image: beefMassaman,
    id: "beef-massaman",
    nuts: false,
    vegeterian: false,
    spiciness: 2,
  },
  {
    name: "Seafood chu chee",
    price: 16,
    category: "seafood-dishes",
    image: chuChee,
    id: "seafood-chu-chee",
    nuts: false,
    vegeterian: false,
    spiciness: 2,
  },
  {
    name: "Penang shrimp",
    price: 16,
    category: "seafood-dishes",
    image: redCurry,
    id: "penang-shrimp",
    nuts: true,
    vegeterian: false,
    spiciness: 4,
  },
  {
    name: "Green curry veggies",
    price: 12.5,
    category: "vegetable-dishes",
    image: greenCurry,
    id: "green-curry-veggies",
    nuts: true,
    vegeterian: true,
    spiciness: 0,
  },
  {
    name: "Tofu cashew",
    price: 12.5,
    category: "vegetable-dishes",
    image: tofuCashew,
    id: "tofu-cashew",
    nuts: true,
    vegeterian: true,
    spiciness: 0,
  },
  {
    name: "Red curry veggies",
    price: 12.5,
    category: "vegetable-dishes",
    image: redCurry,
    id: "red-curry-veggies",
    nuts: false,
    vegeterian: true,
    spiciness: 4,
  },
  {
    name: "Krapau tofu",
    price: 12.5,
    category: "vegetable-dishes",
    image: krapauVega,
    id: "krapau-tofu",
    nuts: false,
    vegeterian: true,
    spiciness: 0,
  },
  {
    name: "Prawn crackers",
    price: 2.5,
    category: "bits-and-bites",
    image: kroepoek,
    id: "prawn-crackers",
    nuts: false,
    vegeterian: false,
    spiciness: 1,
  },
  {
    name: "Fish cakes",
    price: 6.5,
    category: "bits-and-bites",
    image: fishCakes,
    id: "fish-cakes",
    nuts: false,
    vegeterian: false,
    spiciness: 1,
  },
  {
    name: "Chicken satay",
    price: 6.5,
    category: "bits-and-bites",
    image: sate,
    id: "chicken-satay",
    nuts: false,
    vegeterian: false,
    spiciness: 1,
  },
  {
    name: "Satay sauce",
    price: 1.5,
    category: "bits-and-bites",
    image: satesaus,
    id: "satay-sauce",
    nuts: false,
    vegeterian: false,
    spiciness: 2,
  },
  {
    name: "Shrimp springrolls",
    price: 6.5,
    category: "bits-and-bites",
    image: koongHomPha,
    id: "shrimp-springrolls",
    nuts: false,
    vegeterian: false,
    spiciness: 3,
  },
  {
    name: "Mini vegetarian spring rolls",
    price: 6.5,
    category: "bits-and-bites",
    image: springRolls,
    id: "mini-vegetarian-spring-rolls",
    nuts: false,
    vegeterian: false,
    spiciness: 2,
  },
  {
    name: "Chicken springrolls",
    price: 6.5,
    category: "bits-and-bites",
    image: springRolls,
    id: "chicken-springrolls",
    nuts: false,
    vegeterian: false,
    spiciness: 2,
  },
  {
    name: "Thai fried rice",
    price: 7.5,
    category: "on-the-side",
    image: friedRice,
    id: "thai-fried-rice",
    nuts: false,
    vegeterian: false,
    spiciness: 2,
  },
  {
    name: "Prik nam pla",
    price: 0.5,
    category: "on-the-side",
    image: prikNamPla,
    id: "prik-nam-pla",
    nuts: false,
    vegeterian: false,
    spiciness: 4,
  },
  {
    name: "Fresh prawn crackers",
    price: 2.5,
    category: "on-the-side",
    image: kroepoek,
    id: "fresh-prawn-crackers",
    nuts: false,
    vegeterian: false,
    spiciness: 1,
  },
  {
    name: "Stir fried vegetables",
    price: 7.5,
    category: "on-the-side",
    image: stirFriedVegetables,
    id: "stir-fried-vegetables",
    nuts: false,
    vegeterian: true,
    spiciness: 0,
  },
  {
    name: "White rice",
    price: 1.5,
    category: "on-the-side",
    image: witteRijst,
    id: "white-rice",
    nuts: false,
    vegeterian: true,
    spiciness: 0,
  },
  {
    name: "Fried noodles Thai style",
    price: 7.5,
    category: "on-the-side",
    image: friedNoodles,
    id: "fried-noodles-thai-style",
    nuts: false,
    vegeterian: true,
    spiciness: 2,
  },
  {
    name: "King salad",
    price: 7.5,
    category: "on-the-side",
    image: kingSalad,
    id: "king-salad",
    nuts: false,
    vegeterian: true,
    spiciness: 2,
  },
  {
    name: "Satésaus",
    price: 1.5,
    category: "on-the-side",
    image: satesaus,
    id: "sat-saus",
    nuts: false,
    vegeterian: true,
    spiciness: 2,
  },
];

export default products;
